### PR TITLE
Dead proof elimination

### PR DESCRIPTION
**Pull request by adelaett**
This PR aims at cleaning the artifact and improving the documentation.

- [x] Using [dpdgraph](https://github.com/coq-community/coq-dpdgraph) to remove all lemmas unused to show main results.
- [ ] write docstring to each of the lemmas. As well as for files.

### CODE REVIEW

**Comment by adelaett** [comment]
I've added the preservation of the typing for the translation.

**Comment by adelaett** [comment]
As well as some missing rules related to fold in the typing. I went for no_default as hypothesis for this case.

**Comment by adelaett** [comment]
@denismerigoux can you review the change ?

**Comment by denismerigoux** [comment]
I already reviewed this PR and it was OK for me until commit [8fc21e0](https://github.com/CatalaLang/catala-formalization/pull/11/commits/8fc21e0406449f281d46fffb84433f0f201da513) but the CI was red so I was waiting for you to fix it. Why was the CI failing at this point ?

**Comment by denismerigoux** [comment]
Then 10 mins ago you added 2 commits, the latter reverting the former, I don't understand why :)

**Comment by adelaett** [comment]
> Then 10 mins ago you added 2 commits, the latter reverting the former, I don't understand why :)

It was to do something nice for the artifact reviewers: showing what happens if we remove all invariant in the typing judgement.

**Pull request merged**
